# Development/Testing optimized docker-compose override
# This file provides faster startup and optimized settings for development

services:
  neo4j:
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_dbms_jvm_additional=-Xms256m -Xmx512m # Reduced memory for faster startup
      - NEO4J_server_config_strict__validation_enabled=false
      - NEO4J_dbms_transaction_timeout=5s # Faster timeout for tests
      - NEO4J_dbms_lock_acquisition_timeout=5s # Faster lock timeout
      - NEO4J_dbms_checkpoint_interval_time=30s # Faster checkpoints
    healthcheck:
      test:
        ['CMD-SHELL', 'wget --quiet --spider http://localhost:7474 || exit 1']
      interval: 10s # Check more frequently
      timeout: 5s # Faster timeout
      retries: 10 # More retries for reliability
      start_period: 20s # Reduced start period
    restart: unless-stopped # Keep running between test runs
