[test]
# Use happy-dom for DOM testing instead of jsdom
testEnvironment = "happy-dom"

# Test patterns
testMatch = [
  "**/__tests__/**/*.(test|spec).(ts|tsx|js)",
  "**/*.(test|spec).(ts|tsx|js)"
]

# Setup files
setupFilesAfterEnv = ["./src/setupTests.ts"]

# Coverage settings
coverage = true
coverageDirectory = "coverage"
coverageReporters = ["text", "lcov", "html"]

# Module resolution
moduleNameMapping = {
  "\\.(css|less|scss|sass)$" = "identity-obj-proxy"
}

# Preload setup file
preload = ["./src/setupTests.ts"]

# Timeout settings
timeout = 10000